"""add customer_id to orders

Revision ID: 088147e46590
Revises: 002_add_customers_activity
Create Date: 2025-11-28 16:46:03.746720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088147e46590'
down_revision = '002_add_customers_activity'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    except:
        pass  # Index may already exist
    # SQLite doesn't support ALTER COLUMN, skip these:
    # op.alter_column('batches', 'received_date',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # op.alter_column('customers', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('customers', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    
    # Add customer_id column and foreign key using batch mode for SQLite
    with op.batch_alter_table('orders') as batch_op:
        try:
            batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        except:
            pass  # Column may already exist
        try:
            batch_op.create_foreign_key('fk_orders_customer_id', 'customers', ['customer_id'], ['id'])
        except:
            pass  # FK may already exist
        try:
            batch_op.drop_column('supplier_id')
        except:
            pass  # Column may not exist
    
    try:
        op.drop_index('ix_users_email', table_name='users')
    except:
        pass  # Index may not exist
    
    # SQLite doesn't support adding unique constraints directly, skip
    # op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.add_column('orders', sa.Column('supplier_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('batches', 'received_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    # ### end Alembic commands ###

